# Generated by Django 4.0.6 on 2022-10-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_post_category_post_tags_reply_notificaiton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='title',
        ),
    ]
