# Generated by Django 4.0.6 on 2022-10-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_category_title_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
