# Generated by Django 4.0.6 on 2022-10-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
