# Generated by Django 4.0.6 on 2022-10-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaiton',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notificaiton',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notificaiton',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
