# Generated by Django 4.0.6 on 2022-10-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_product_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='notes_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subject',
        ),
    ]
