# Generated by Django 4.0.6 on 2022-10-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_rename_category_product_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Notes',
        ),
    ]
