# Generated by Django 4.0.6 on 2022-10-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_rename_product_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default='', upload_to='education/images'),
        ),
    ]
