# Generated by Django 4.0.6 on 2022-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_notes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='price',
        ),
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
