# Generated by Django 4.0.6 on 2022-10-12 14:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_notes_price_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes_name',
            field=models.CharField(max_length=300),
        ),
    ]
