# Generated by Django 4.0.6 on 2023-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_remove_product_category_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.IntegerField(null=True),
        ),
    ]
