# Generated by Django 4.0.6 on 2023-01-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Image',
        ),
    ]
