# Generated by Django 4.1.5 on 2023-01-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_image_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Categories',
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.DeleteModel(
            name='Additional_Information',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product_Image',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
