# Generated by Django 4.1.5 on 2023-01-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_alter_product_table_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Categories',
            new_name='categories',
        ),
    ]
