# Generated by Django 4.1.5 on 2023-01-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_categories_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
